global_costmap:
  global_frame: world
  robot_base_frame: body_foot

  update_frequency: 1
  publish_frequency: 1
  transform_tolerance: 0.5

  static_map: false
  width: 140
  height: 80
  resolution: 1
  # rolling_window: true
  origin_x: -10.0 
  origin_y: -40.0
 
